### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by ahmad2smile** [mbasso/asm-dom-boilerplate#1]
I was planing to do something with just raw emcc complier and C++ but then I found this project. Its amazing. 

I think at the very least Ho Reloading is very important for anyone coming from Web background to this project if not Hot Module Replacement.

I know C++ is a different universe then the whole JS things but I've worked with ASP.NET Core in C# and they got Hot Reloading and somewhat HMR too, So maybe in theory it can be done with C++.

 If it can be implemented it be huge thing for this project.

**Comment by mbasso** [comment]
Hi @ahmad2smile,
thank you for your interest in asm-dom and for opening this issue 😄
Yeah, I think that this is a great idea. we can automatically recompile `.cpp` files to `.wasm` and `.asm.js` on change and then reload to page using `parcel`.
I've just seen that you have submitted a PR, I'll review it as soon as possible!
