### ISSUE TITLE
Java is Required

### ISSUE THREAD

**Issue by s0kil** [mbasso/asm-dom-boilerplate#6]
I followed the getting started instructions in the readme.
And got the following error:
```bash
WARNING:root:java does not seem to exist, required for closure compiler, which is optional (define JAVA in /home/danielsokil/.emscripten if you want it)
ERROR:root:fatal: closure compiler is not configured correctly
Makefile:104: recipe for target 'dist/wasm' failed
make: *** [dist/wasm] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! asm-dom-boilerplate@0.1.0 start: `make start`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the asm-dom-boilerplate@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danielsokil/.npm/_logs/2018-09-19T00_44_50_521Z-debug.log
```
After installing `sudo apt-get install default-jdk` Java, `npm start` is successful.

**Comment by mbasso** [comment]
Hi @DanielSokil,
Java is required by emscripten to run the closure compiler, but it seems that it has to be installed manually on Linux. [here](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#platform-notes-installation-instructions-sdk) is the installation guide of emscripten. Do you think that we should add a note in the readme?

**Comment by s0kil** [comment]
@mbasso Yeah, it's a good idea to add to readme.

**Comment by mbasso** [comment]
Just added java to the prerequisites. Let me know if it is ok.
Thank you for opening this issue 😄
